### ISSUE TITLE
Enum with BigDecimal/Integer Values is converted into enum string instead of number

### ISSUE THREAD

**Issue by bhargavmummini** [youengineering/openapi-maven-plugin#8]
Consider the following enum as an attribute in response model.

```
    public enum Duration{
        NUMBER_0(new BigDecimal("0")),
        NUMBER_12(new BigDecimal("12")),
        NUMBER_24(new BigDecimal("24"));

        private final BigDecimal value;

        Duration(final BigDecimal value) {
            this.value = value;
        }

        @JsonValue
        public BigDecimal getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }
    }
```

Then under openapi.yaml it is getting generated as enum of string

```
 duration:
  type: string
  enum:
  - "0"
  - "12"
   - "24"
```

expected
```
duration:
  type: number
  enum:
  - 0
  - 12
  - 24
```
